# Generated by Django 6.0.2 on 2026-02-20 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("procedure", "Procedure"),
                            ("diagram", "Architecture diagram"),
                            ("ticket", "Change ticket"),
                            ("log", "Log / monitoring"),
                            ("attestation", "Interview / attestation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["name"], "unique_together": {("name",)},},
        ),
        migrations.CreateModel(
            name="ControlSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name", "version"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("control_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=64)),
                (
                    "control_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="irap.controlset",
                    ),
                ),
            ],
            options={"ordering": ["control_set__name", "control_id"],},
        ),
        migrations.CreateModel(
            name="BoundaryAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "boundary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_associations",
                        to="irap.boundary",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_associations",
                        to="irap.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url_or_reference", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="irap.evidence",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="EvidenceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_usages",
                        to="irap.control",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_usages",
                        to="irap.evidence",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidence",
            name="controls",
            field=models.ManyToManyField(
                related_name="evidence_items",
                through="irap.EvidenceUsage",
                to="irap.control",
            ),
        ),
        migrations.CreateModel(
            name="ControlAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not assessed"),
                            ("pass", "Pass"),
                            ("partial", "Partial"),
                            ("fail", "Fail"),
                            ("n_a", "Not applicable"),
                        ],
                        default="not_assessed",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="irap.control",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["control", "-assessment_date"],
                        name="irap_contro_control_7d87bf_idx",
                    ),
                    models.Index(
                        fields=["status"], name="irap_contro_status_869288_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(
                fields=["control_id"], name="irap_contro_control_701e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(fields=["name"], name="irap_contro_name_54f51d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="control", unique_together={("control_set", "control_id", "version")},
        ),
        migrations.AddIndex(
            model_name="boundaryassociation",
            index=models.Index(
                fields=["boundary"], name="irap_bounda_boundar_240b0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boundaryassociation",
            index=models.Index(
                fields=["evidence", "boundary"], name="irap_bounda_evidenc_c3f65b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boundaryassociation", unique_together={("evidence", "boundary")},
        ),
        migrations.AddIndex(
            model_name="evidenceusage",
            index=models.Index(
                fields=["control", "evidence"], name="irap_eviden_control_f00f0f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evidenceusage", unique_together={("control", "evidence")},
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["type"], name="irap_eviden_type_e43a99_idx"),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["name"], name="irap_eviden_name_af668e_idx"),
        ),
    ]
