# Generated by Django 6.0.2 on 2026-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boundary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="boundaryassociation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="control",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="controlassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="controlset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="evidenceusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
